In [1]:
import numpy as np

In [2]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
A.ndim

2

In [5]:
A.shape

(3, 3)

In [6]:
A.size

9

In [7]:
A[1,2]

np.int64(23)

In [8]:
A[1][2]

np.int64(23)

In [10]:
A[0][0]

np.int64(11)

In [11]:
A[0][0:2]

array([11, 12])

In [12]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [13]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [15]:
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [16]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [17]:
Z = 2*Y
Z

array([[4, 2],
       [2, 4]])

In [18]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [19]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [20]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [21]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [22]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [23]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [24]:
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [25]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [26]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [27]:
C.T

array([[1, 2, 3],
       [1, 2, 3]])